name: 'My Hello World Container Action'
description: 'Prints Hello, World!'
inputs:
  who-to-greet:
    description: 'Person to greet'
    required: false
    default: 'World'
runs:
  using: 'docker'
  image: 'Dockerfile'
