name: Run Hello World Action

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run my container action
        uses: ./
        with:
          who-to-greet: 'GitHub User'
